"""
GENERATED BY CLAUDE ON 07/04/2026
fit_load_profile.py
===================
Fit a load factor profile (weekday + weekend, 24-hour) so that the
combined weekly TOU energy fractions match target ratios derived from
real electricity bills.

The function takes:
  • a base Abagold-style profile  (initial shape)
  • a TOU billing schedule        (which hours are PK / STD / OP)
  • target TOU energy ratios      (from real bills)

It returns (and optionally saves) a new profile whose shape is as close
as possible to the original while hitting the target ratios.

Usage
-----
    from fit_load_profile import fit_load_profile

    df = fit_load_profile(
        tou_ratios_path    = "time_of_use_ratios.csv",
        tou_schedule_path  = "time_of_use_25-26.csv",
        base_profile_path  = "Abagold.csv",
        output_path        = "fitted_profile.csv",   # optional
    )
    print(df)

CSV formats expected
--------------------
time_of_use_ratios.csv
    period, ratio
    PK, 0.1725
    STD, 0.3308
    OP, 0.4966

time_of_use_25-26.csv
    season, DayType, time, TOU
    low, Weekday, 06:00, STD
    low, Weekday, 07:00, PK
    ...    (DayType values: Weekday / Sat / Sun)

Abagold.csv  (base profile)
    Hour, WeekdayLoadFactor, WeekendLoadFactor
    0, 0.85, 0.85
    1, 0.85, 0.85
    ...
"""

import numpy as np
import pandas as pd
from scipy.optimize import minimize


def fit_load_profile(
    tou_ratios_path: str,
    tou_schedule_path: str,
    base_profile_path: str,
    season_weights: dict | None = None,
    day_weights: dict | None = None,
    output_path: str | None = None,
    verbose: bool = True,
) -> pd.DataFrame:
    """
    Fit a load factor profile so combined weekly TOU energy fractions
    match the billing-derived target ratios.

    Method
    ------
    Three scale factors (one per TOU band: PK, STD, OP) are found by
    minimising the squared difference between achieved and target energy
    fractions.  Both weekday and weekend load factors are scaled by the
    same set of factors, preserving within-band shape while adjusting
    the overall split between bands.

    The "achieved" fractions are computed as a weighted combination of:
      • season (e.g. low / high) — weighted by season_weights
      • day type (Weekday / Weekend) — weighted by day_weights

    Hours that fall in different TOU bands across seasons receive a
    blended effective weight automatically.

    Parameters
    ----------
    tou_ratios_path : str
        Path to CSV with columns ['period', 'ratio'].
        period values must be 'PK', 'STD', 'OP'. Ratios should sum to 1.
    tou_schedule_path : str
        Path to CSV with columns ['season', 'DayType', 'time', 'TOU'].
        DayType: 'Weekday', 'Sat', 'Sun'.
        time: 'HH:MM' (one row per hour per season/day-type).
        TOU: 'PK', 'STD', or 'OP'.
    base_profile_path : str
        Path to CSV with columns ['Hour', 'WeekdayLoadFactor',
        'WeekendLoadFactor'].  24 rows (Hour 0–23).
    season_weights : dict, optional
        Relative weight for each season, e.g. {'low': 0.5, 'high': 0.5}.
        Defaults to equal weighting across all seasons found in the schedule.
    day_weights : dict, optional
        Relative weight for weekday vs weekend hours in the optimisation.
        Default: {'Weekday': 5, 'Weekend': 2} (Mon–Fri vs Sat–Sun).
    output_path : str, optional
        If given, the fitted profile is saved as a CSV to this path.
    verbose : bool
        Print scale factors and achieved vs target fractions. Default True.

    Returns
    -------
    pd.DataFrame
        Columns: ['Hour', 'WeekdayLoadFactor', 'WeekendLoadFactor']
        24 rows, values rounded to 4 decimal places.

    Raises
    ------
    ValueError
        If required columns are missing from any input file.
    """

    BANDS = ["PK", "STD", "OP"]

    # ── 1. Load & validate inputs ──────────────────────────────────────────────
    ratios_df = pd.read_csv(tou_ratios_path)
    ratios_df.columns = ratios_df.columns.str.strip()
    _require_cols(ratios_df, ["period", "ratio"], tou_ratios_path)
    target: dict[str, float] = ratios_df.set_index("period")["ratio"].to_dict()
    for b in BANDS:
        if b not in target:
            raise ValueError(f"Band '{b}' missing from {tou_ratios_path}")

    schedule = pd.read_csv(tou_schedule_path)
    _require_cols(schedule, ["season", "DayType", "time", "TOU"], tou_schedule_path)
    schedule["hour"] = schedule["time"].str[:2].astype(int)
    schedule["day_category"] = schedule["DayType"].map(
        {"Weekday": "Weekday", "Sat": "Weekend", "Sun": "Weekend"}
    )

    base = pd.read_csv(base_profile_path)
    _require_cols(base, ["Hour", "WeekdayLoadFactor", "WeekendLoadFactor"],
                  base_profile_path)
    base = base.set_index("Hour")

    # ── 2. Normalise weights ───────────────────────────────────────────────────
    seasons = list(schedule["season"].unique())
    if season_weights is None:
        season_weights = {s: 1.0 / len(seasons) for s in seasons}
    season_weights = _normalise(season_weights)

    if day_weights is None:
        day_weights = {"Weekday": 5, "Weekend": 2}
    day_weights = _normalise(day_weights)

    # ── 3. Build effective TOU weight matrices ─────────────────────────────────
    # eff_X[h][b]  = fraction of energy at hour h attributed to band b,
    #                after averaging across seasons (and Sat/Sun sub-types).
    eff_wd = _effective_tou(schedule, "Weekday", season_weights, BANDS)
    eff_we = _effective_tou(schedule, "Weekend", season_weights, BANDS)

    # ── 4. Optimise three scale factors ───────────────────────────────────────
    base_wd = base["WeekdayLoadFactor"].values.copy()
    base_we = base["WeekendLoadFactor"].values.copy()

    def _fractions(x: np.ndarray) -> dict[str, float]:
        """Compute combined weekly TOU fractions for scale vector x."""
        scales = dict(zip(BANDS, x))
        lf_wd = _apply_scales(base_wd, eff_wd, scales, BANDS)
        lf_we = _apply_scales(base_we, eff_we, scales, BANDS)
        energy = {b: 0.0 for b in BANDS}
        total = 0.0
        for h in range(24):
            for b in BANDS:
                e = (day_weights["Weekday"] * lf_wd[h] * eff_wd[h][b]
                     + day_weights["Weekend"] * lf_we[h] * eff_we[h][b])
                energy[b] += e
                total += e
        return {b: energy[b] / total for b in BANDS}

    def objective(x: np.ndarray) -> float:
        fracs = _fractions(x)
        err = sum((fracs[b] - target[b]) ** 2 for b in BANDS)
        reg = 1e-4 * sum((xi - 1.0) ** 2 for xi in x)   # prefer scales ≈ 1
        return err + reg

    result = minimize(
        objective,
        x0=np.ones(3),
        bounds=[(0.01, 50.0)] * 3,
        method="L-BFGS-B",
        options={"ftol": 1e-15, "gtol": 1e-10, "maxiter": 50_000},
    )

    opt_scales = dict(zip(BANDS, result.x))
    lf_wd_new = _apply_scales(base_wd, eff_wd, opt_scales, BANDS)
    lf_we_new = _apply_scales(base_we, eff_we, opt_scales, BANDS)
    achieved = _fractions(result.x)

    # ── 5. Diagnostics ─────────────────────────────────────────────────────────
    if verbose:
        print("Scale factors applied:")
        for b in BANDS:
            print(f"  {b}: {opt_scales[b]:.4f}")
        print("\nTOU energy fractions (combined weekly):")
        print(f"  {'Band':<6} {'Target':>8} {'Achieved':>10} {'Error':>8}")
        for b in BANDS:
            err = achieved[b] - target[b]
            print(f"  {b:<6} {target[b]:>8.4f} {achieved[b]:>10.4f} {err:>+8.4f}")

    # ── 6. Assemble output ─────────────────────────────────────────────────────
    out = pd.DataFrame({
        "Hour": range(24),
        "WeekdayLoadFactor": np.round(lf_wd_new, 4),
        "WeekendLoadFactor": np.round(lf_we_new, 4),
    })

    if output_path:
        out.to_csv(output_path, index=False)
        if verbose:
            print(f"\nSaved → {output_path}")

    return out


# ── Private helpers ────────────────────────────────────────────────────────────

def _require_cols(df: pd.DataFrame, cols: list[str], path: str) -> None:
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing columns {missing} in {path}. "
                         f"Found: {list(df.columns)}")


def _normalise(d: dict) -> dict:
    total = sum(d.values())
    return {k: v / total for k, v in d.items()}


def _effective_tou(
    schedule: pd.DataFrame,
    day_cat: str,
    season_weights: dict,
    bands: list[str],
) -> list[dict[str, float]]:
    """
    For each of the 24 hours, return the fraction of energy attributable
    to each TOU band, after averaging across seasons (and across multiple
    DayType rows that map to the same day_category, e.g. Sat + Sun).
    """
    eff = []
    for h in range(24):
        bw = {b: 0.0 for b in bands}
        for season, sw in season_weights.items():
            rows = schedule[
                (schedule["season"] == season)
                & (schedule["day_category"] == day_cat)
                & (schedule["hour"] == h)
            ]
            if rows.empty:
                continue
            n = len(rows)
            for _, row in rows.iterrows():
                bw[row["TOU"]] += sw / n
        eff.append(bw)
    return eff


def _apply_scales(
    base_lf: np.ndarray,
    eff: list[dict[str, float]],
    scales: dict[str, float],
    bands: list[str],
) -> np.ndarray:
    """Scale a 24-element load-factor array by per-band scale factors."""
    lf = np.empty(24)
    for h in range(24):
        lf[h] = base_lf[h] * sum(scales[b] * eff[h][b] for b in bands)
    return lf


# ── CLI convenience ────────────────────────────────────────────────────────────
# Terminal usage:
# python profile_from_tou_ratio.py ratios.csv schedule.csv load_factor_base.csv
# -o output.csv

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Fit a load factor profile to TOU billing ratios."
    )
    parser.add_argument("ratios",   help="Path to time_of_use_ratios.csv")
    parser.add_argument("schedule", help="Path to time_of_use_25-26.csv")
    parser.add_argument("base",     help="Path to base profile CSV (e.g. Abagold.csv)")
    parser.add_argument("-o", "--output", default=None,
                        help="Output CSV path (default: print only)")
    args = parser.parse_args()

    df = fit_load_profile(
        tou_ratios_path=args.ratios,
        tou_schedule_path=args.schedule,
        base_profile_path=args.base,
        output_path=args.output,
    )
    print("\nFitted profile:")
    print(df.to_string(index=False))